### ISSUE TITLE
[Selene] Name already taken, in reference to a Lua thing already?

### ISSUE THREAD

**Issue by ChickenNuggers** [OpenPrograms/Vexatos-Programs#15]
Was in [#lua](irc://irc.freenode.net/lua) when I saw (this)[https://github.com/jeremyong/Selene] posted?

**Comment by Vexatos** [comment]
I know it is, but there is no copyright on the name so it's fine to have multiple things with the same name. I doubt it'll be confusing as those two things are completely different and probably wouldn't ever be used together anyway :palm_tree:
