### ISSUE TITLE
[OPPM] Avoid deleting the configuration files on update

### ISSUE THREAD

**Issue by stsimonas** [OpenPrograms/Vexatos-Programs#17]
For a user who has some local packages configured in the **oppm.cfg**, running **oppm update all** overwrites the **oppm.cfg** with a blank new one - no local packages get updated as all local configurations have been lost.

The _oppm local packages_ case points towards a bigger design idea: **avoid deleting/overwriting package configuration files on package update**.

I think something such as an additional flag for the repository/package files table would do the trick. Although the below idea would also require a new flag for uninstalling packages (full uninstall - deletes config files as well)

``` lua
files = {
    ["master/somefolder/bar.lua"] = "/",--"/" means the file will be placed inside the folder the user specified, defaults to /usr
    ["master/somefolder/barinfo.txt"] = "//etc", -- double slash for using an absolute path
    [":master/otherfolder"] = "/share/something", -- A colon marks a folder, will include everything in that folder
    [":master/otherfolder"] = "//etc/something", -- This also works with absolute paths
    ["master/somefolder/barlib.lua"] = "/subfolder",--Places the file in a subfolder in the user-specified folder
    ["master/somefolder/libfolder/"] = "/"

    ["$master/configfolder"] = "/etc" -- A dolar sign marks a folder/file to only download the files if they are not present. Useful for configuration files that should not be overwritten.
},
```

**Comment by AR2000AR** [comment]
You can prefix a path with `?` to not overwrite the file. This is already a feature, but it only work on single files, not folders. Not sure it was a thing when this issue was posted, but was is when I posted my comment.
