### ISSUE TITLE
Add bitcoin transactions to OPPM

### ISSUE THREAD

**Issue by SoniEx2** [OpenPrograms/Vexatos-Programs#19]
There should be an API where paid programs can be distributed through OPPM. You buy a program with a bitcoin transaction and once the transaction is confirmed the download starts.

Someone else can make a bitcoin wallet for OC.

**Comment by Vexatos** [comment]
Well, make one yourself.

**Comment by BrewAndCode** [comment]
doesn't sound very "open" to me.. but what do I know

**Comment by reinei** [comment]
A package mangager isn't supposed to buy programms, is supposed to manage them.
If you want to distribute Programms via paywall, just use a normal downloader Programm and let it be installed ...

**Comment by SoniEx2** [comment]
@BrewAndCode I thought the "open" was about the package manager, not the programs it manages...

@reinei *Manages* the buying and the downloading of a *package*.  Still a package manager. - Windows store, google play and app store are all package managers, even if they lack many features of standard package managers. Alternatively, cydia is a fully featured package manager and includes paid packages.
