### ISSUE TITLE
[OPPM] Issue updating package with high dependency depth

### ISSUE THREAD

**Issue by linuxdaemon** [OpenPrograms/Vexatos-Programs#25]
When installing package A which depends on B which depends on C, package A is not recorded in `/etc/opdata.svd` but B and C are. This means `oppm update A` fails with `Error while checking update path` but updating B and C works fine. Seems to be an issue with 

https://github.com/OpenPrograms/Vexatos-Programs/blob/cd3239d5d6bb67d4f499791ffcac65dc5cda37fe/oppm/oppm.lua#L554-L557

**Comment by Vexatos** [comment]
Thanks for the report. Could you try running `oppm update oppm` and see whether the new version fixes it?

**Comment by linuxdaemon** [comment]
Yep that seems to have fixed it
