### ISSUE TITLE
[OPPM] Update doesn't seem to always work with locally registered repository

### ISSUE THREAD

**Issue by aphistic** [OpenPrograms/Vexatos-Programs#26]
I've recently started using OpenComputers and I'm working on my first OC program using OPPM to handle installation.  I have my repository (https://github.com/aphistic/oc-programs) registered locally and I've been able to install my program successfully but when I push a new commit and do a `oppm update aphstore` it acts as if it's downloading a new version (it says it's updating the package, removing old files, etc) but it still uses the old version of the files.  I've been trying to figure out what causes it to eventually install the newest version but I haven't been able to find it.  Github shows the new version of the file and doing a new `oppm list` doesn't seem to update it either.  I did a search of the existing issues but I couldn't find anything related to this.  Is this a known issue? Am I using OPPM incorrectly?

**Comment by Vexatos** [comment]
GitHub may take five to ten minutes after pushing to actually update the data on the API side; after pushing an update you should wait about five minutes and try it. Will it work then?

**Comment by aphistic** [comment]
Ahh, that's probably it then. It does update after a few minutes. I didn't realize it was using an API to pull it instead of doing a git clone. Do you have a way you iterate on OC programs installed with OPPM? Writing some code, pushing it and then waiting some minutes for updates takes a long time.  Thanks for the response, though! I'll close the issue and do some searching on my own as well. :)

**Comment by Vexatos** [comment]
Cloning all git repos would take way too long on these computers.

Data on installed programs are stored in `/etc/opdata.svd`; the format is very simple and should be easy to parse.
