### ISSUE TITLE
[OPPM] table not correctly copied break parseFolders

### ISSUE THREAD

**Issue by AR2000AR** [OpenPrograms/Vexatos-Programs#30]
[https://github.com/OpenPrograms/Vexatos-Programs/blob/5ff6db8c89dcbb80b7493364768542542d411171/oppm/oppm.lua#L301](https://github.com/OpenPrograms/Vexatos-Programs/blob/5ff6db8c89dcbb80b7493364768542542d411171/oppm/oppm.lua#L301)
I found this bug in oppm while working on something else.  
This line meant to make a copy of the table but that's not how lua work. It just make a reference to the table. For a copy you would need a `deepcopy` function.
```lua
local function deepcopy(orig)
    local orig_type = type(orig)
    local copy
    if orig_type == 'table' then
        copy = {}
        for orig_key, orig_value in next, orig, nil do
            copy[deepcopy(orig_key)] = deepcopy(orig_value)
        end
        setmetatable(copy, deepcopy(getmetatable(orig)))
    else -- number, string, boolean, etc
        copy = orig
    end
    return copy
end
```
Lua version : 5.3
What should happen (and does with a deepcopy) ;
![expected result](https://cdn.discordapp.com/attachments/125649403162656768/1065276319644000326/image.png)
What really happen :
![what happen](https://cdn.discordapp.com/attachments/125649403162656768/1065276350220484648/image.png)

**Comment by Vexatos** [comment]
Fixed with 47ae6d628c0d44f2e8f86f9f632c177658f9efb0.
